development:
  adapter: postgresql
  encoding: unicode
  database: ftsp_dev
  pool: 5
  username: bparanj
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: ftsp_test
  pool: 5
  username: bparanj
  password: